#WorldSeed: myseed123

ListenAddress: 0.0.0.0
ListenPort: 9000

DataDir: data/
ChunksDir: data/chunks/
ChunkSize: 30
BadgerDir: data/badger/

WorldMaxAltitude: 30
ChunkLoadRadius: 1
ChunkLoadPadding: 2

AuthTokenKey: ChangeMe123!
